# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThM.q
#$ -l mres=96G,h_data=96G,h_vmem=200G,himem
#$ -cwd
#$ -j y
#$ -N make_blast_database
#$ -o logs/make_blast_database.log
#
# ----------------Modules------------------------- #
module load bioinformatics/blast

#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS


# This starts a blastn search against your reference database
# replace -query with the path to your representative sequence fasta
# replace -out with your desired out path.
# replace -db with the database you want to use. I don't know what is available
# on hydra currently
# Everything else should work
makeblastdb \
-in reference_database.fasta \
-dbtype nucl \
-out databasename

echo = `date` job $JOB_NAME done