# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 4
#$ -q sThC.q
#$ -l mres=8G,h_data=2G,h_vmem=2G
#$ -cwd
#$ -j y
#$ -N trimmed
#$ -o trimmed.log
#
# ----------------Modules------------------------- #
module load bioinformatics/cutadapt/4.7
module load tools/R/4.4.1
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
data="$1"
gene1="$2"
gene2="$3"
primerF="$4" 
primerR="$5" 
primerFrc="$6"
primerRrc="$7"

#echo $data
#echo $gene1
#echo $gene2
#echo $primerF
#echo $primerR
echo $primerFrc
echo $primerRrc

for x in ${data}/raw/*_R1*; do
  sample=`basename ${x}`
  name=`echo ${sample%*_R[1-2]_*}`
  namepost=`echo ${sample#*_R[1-2]*}`
#echo $sample
#echo $name
#echo $namepost

if [ -v ${primerFrc} ]; then
  echo "We will first attempt to remove 3' primers"
  
  cutadapt \
  -a file:${data}/../primers/${primerRrc} \
  -A file:${data}/../primers/${primerFrc} \
  -e 0.2 --cores=$NSLOTS -O 3 \
  -o ${data}/raw/${name}_trimmed_R1.fastq \
  -p ${data}/raw/${name}_trimmed_R2.fastq \
  ${data}/raw/${name}_R1_${namepost} \
  ${data}/raw/${name}_R2_${namepost}
  
  echo "We will next remove 5' primers"
  
  cutadapt \
  -g file:${data}/../primers/${primerF} \
  -G file:${data}/../primers/${primerR} \
  -e 0.2 --minimum-length 30 --cores=$NSLOTS --discard-untrimmed --quiet --nextseq-trim=20 \
  -o ${data}/working/trimmed_sequences/{name}/${name}_trimmed_R1.fastq \
  -p ${data}/working/trimmed_sequences/{name}/${name}_trimmed_R2.fastq \
  ${data}/raw/${name}_trimmed_R1.fastq \
  ${data}/raw/${name}_trimmed_R2.fastq

#  rm ${data}/raw/${name}_trimmed_R1.fastq ${data}/raw/${name}_trimmed_R2.fastq

else
  echo "We will only attempt to remove 5' primers"
  cutadapt \
  -g file:${data}/../primers/${primerF} \
  -G file:${data}/../primers/${primerR} \
  -e 0.2 --minimum-length 30 --cores=$NSLOTS --discard-untrimmed --quiet --nextseq-trim=20 \
  -o ${data}/working/trimmed_sequences/{name}/${name}_trimmed_R1.fastq \
  -p ${data}/working/trimmed_sequences/{name}/${name}_trimmed_R2.fastq \
  ${data}/raw/${name}_trimmed_R1.fastq \
  ${data}/raw/${name}_trimmed_R2.fastq
fi

gzip -2 \
${data}/working/trimmed_sequences/${gene1}/${name}_trimmed_R1.fastq \
${data}/working/trimmed_sequences/${gene1}/${name}_trimmed_R2.fastq \
${data}/working/trimmed_sequences/${gene2}/${name}_trimmed_R1.fastq \
${data}/working/trimmed_sequences/${gene2}/${name}_trimmed_R2.fastq

done

Rscript quality_multigene.R ${gene1} ${gene2}


echo = `date` job $JOB_NAME done