# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 4
#$ -q sThC.q
#$ -l mres=8G,h_data=2G,h_vmem=2G
#$ -cwd
#$ -j y
#$ -N trimmed
#$ -o trimmed.log
#
# ----------------Modules------------------------- #
module load bioinformatics/cutadapt/4.7
module load tools/R/4.4.1
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#

data="$1"
primerF="$2" 
primerR="$3"
primerFrc="$4"
primerRrc="$5"


for x in ${data}/raw/*_R1*; do
  sample=`basename ${x}`
  name=$(echo ${sample%%_S[0-9][0-9][0-9]*}) 
  namepost=`echo ${sample#*_R[1-2]*}`
  namepre=`echo ${sample%*_R[1-2]*}`
if [ ! -z ${primerFrc} ]; then
  echo "We will first trim 3' primers"

  cutadapt \
  -a file:${data}/../primers/${primerRrc} \
  -A file:${data}/../primers/${primerFrc} \
  -e 0.2 --cores=$NSLOTS -O 10 \
  -o ${data}/raw/${name}_trimmed_R1.fastq \
  -p ${data}/raw/${name}_trimmed_R2.fastq \
  ${data}/raw/${namepre}_R1${namepost} \
  ${data}/raw/${namepre}_R2${namepost}

  echo "We will next trim 5' primers, discarding untrimmed"

  cutadapt \
  -g file:${data}/../primers/${primerF} \
  -G file:${data}/../primers/${primerR} \
  -e 0.2 --minimum-length 30 --cores=$NSLOTS --discard-untrimmed \
  --nextseq-trim=20 \
  -o ${data}/working/trimmed_sequences/${name}_trimmed_R1.fastq \
  -p ${data}/working/trimmed_sequences/${name}_trimmed_R2.fastq \
  ${data}/raw/${name}_trimmed_R1.fastq \
  ${data}/raw/${name}_trimmed_R2.fastq
  
rm ${data}/raw/${name}_trimmed_R1.fastq ${data}/raw/${name}_trimmed_R2.fastq

else
  echo "We will trim 5' primers, skipping 3' trimming discarding untrimmed"
  cutadapt \
  -g file:${data}/../primers/${primerF} \
  -G file:${data}/../primers/${primerR} \
  -e 0.2 --minimum-length 30 --cores=$NSLOTS --discard-untrimmed \
  --nextseq-trim=20 \
  -o ${data}/working/trimmed_sequences/${name}_trimmed_R1.fastq \
  -p ${data}/working/trimmed_sequences/${name}_trimmed_R2.fastq \
  ${data}/raw/${namepre}_R1${namepost} \
  ${data}/raw/${namepre}_R2${namepost}
fi

gzip -2 \
${data}/working/trimmed_sequences/${name}_trimmed_R1.fastq \
${data}/working/trimmed_sequences/${name}_trimmed_R2.fastq 

done
Rscript 2_quality.R

echo = `date` job $JOB_NAME done