# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 4
#$ -q sThC.q
#$ -l mres=8G,h_data=2G,h_vmem=2G
#$ -cwd
#$ -j y
#$ -N trimmed
#$ -o trimmed.log
#
# ----------------Modules------------------------- #
module load bioinformatics/cutadapt/4.7
module load tools/R/4.4.1
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#

data="$1"
primerF="$2" 
primerR="$3" 


for x in ${data}/raw/*_R1*; do
  sample=`basename ${x}`
  name=`echo ${sample%*_R[1-2]_*}` 
  namepre=`echo ${sample%_R*}`
  namepost=`echo ${sample#*_R[1-2]_*}`

  cutadapt \
  -g file:${primerF} \
  -G file:${primerR} \
  -e 0.2 --minimum-length 30 --cores=$NSLOTS --discard-untrimmed --quiet --nextseq-trim=20 \
  -o ${data}/working/trimmed_reads/${name}_trimmed_R1.fastq.gz \
  -p ${data}/working/trimmed_reads/${name}_trimmed_R2.fastq.gz \
  ${data}/raw/${namepre}_R1_${namepost} \
  ${data}/raw/${namepre}_R2_${namepost}
done

Rscript quality_plot.R


echo = `date` job $JOB_NAME done