# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 8
#$ -q sThC.q
#$ -l mres=8G,h_data=1G,h_vmem=1G
#$ -cwd
#$ -j y
#$ -N project
#$ -o project.log
#
# ----------------Modules------------------------- #
module load bioinformatics/cutadapt/4.7
module load tools/R/4.4.1
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
data="$1"
gene1="$2"
gene2="$3"
primerF="$4" 
primerR="$5" 
primerFrc="$6"
primerRrc="$7"

#echo $data
#echo $gene1
#echo $gene2
#echo $primerF
#echo $primerR
#echo $primerFrc
#echo $primerRrc

for x in ${data}/raw/*_R1*; do
  sample=`basename ${x}`
  name=`echo ${sample%*_R[1-2]*}`
  namepost=`echo ${sample#*_R[1-2]*}`
#echo $sample
#echo $name
#echo $namepost

if
  [[ -z ${primerFrc} ]]
then
  cutadapt \
  -g file:${data}/../primers/${primerF} \
  -G file:${data}/../primers/${primerR} \
  -e 0.2 --minimum-length 30 --cores=$NSLOTS --discard-untrimmed --report=minimal --nextseq-trim=20 \
  -o ${data}/working/trimmed_reads/{name}/${name}_trimmed_R1.fastq \
  -p ${data}/working/trimmed_reads/{name}/${name}_trimmed_R2.fastq \
  ${data}/raw/${name}_R1${namepost} \
  ${data}/raw/${name}_R2${namepost}
else
  cutadapt \
  -g file:${data}/../primers/${primerF} \
  -a file:${data}/../primers/${primerRrc} \
  -G file:${data}/../primers/${primerR} \
  -A file:${data}/../primers/${primerFrc} \
  -e 0.2 --minimum-length 30 --cores=$NSLOTS -n 2 -O 3 --discard-untrimmed --report=minimal --nextseq-trim=20 \
  -o ${data}/working/trimmed_reads/{name}/${name}_trimmed_R1.fastq \
  -p ${data}/working/trimmed_reads/{name}/${name}_trimmed_R2.fastq \
  ${data}/raw/${name}_R1${namepost} \
  ${data}/raw/${name}_R2${namepost}
fi

done

Rscript quality_plot_multigene.R ${gene1} ${gene2}


echo = `date` job $JOB_NAME done