# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 8
#$ -q sThC.q
#$ -l mres=8G,h_data=1G,h_vmem=1G
#$ -cwd
#$ -j y
#$ -N project
#$ -o project.log
#
# ----------------Modules------------------------- #
module load bioinformatics/cutadapt/4.7
module load tools/R/4.4.1
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#

data="$1"
primer1F="$2" 
primer1R="$3" 
primerFrc="$4"
primerRrc="$5"
gene1="$6"
gene2="$7"
raw="$8"

for x in ${data}/raw/*_R1*; do
  sample=`basename ${x}`
  name=`echo ${sample%%_*}`  
  namepre=`echo ${sample%_R*}`
  namepost=`echo ${sample#*_R[1-2]*}`

if
  [[ -z $4 ]]
then
  cutadapt \
  -g file:${primerF} \
  -G file:${primerR} \
  -e 0.2 --minimum-length 30 --cores=$NSLOTS --discard-untrimmed --report=minimal \
  -o ${data}/working/trimmed_reads/{name}/${name}_trimmed_R1.fastq.gz \
  -p ${data}/working/trimmed_reads/{name}/${name}_trimmed_R2.fastq.gz \
  ${data}/raw/${namepre}_R1${namepost} \
  ${data}/raw/${namepre}_R2${namepost}
else
  cutadapt \
  -g file:${primerF} \
  -a file:${primerRrc} \
  -G file:${primerR} \
  -A file:${primerFrc} \
  -e 0.2 --minimum-length 30 --cores=$NSLOTS -n 2 -O 3 --discard-untrimmed --report=minimal \
  -o ${data}/working/trimmed_reads/{name}/${name}_trimmed_R1.fastq.gz \
  -p ${data}/working/trimmed_reads/{name}/${name}_trimmed_R2.fastq.gz \
  ${data}/raw/${namepre}_R1${namepost} \
  ${data}/raw/${namepre}_R2${namepost}
fi

done

Rscript quality_plot_multigene.R ${gene1} ${gene2}


echo = `date` job $JOB_NAME done