# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 4
#$ -q sThC.q
#$ -l mres=8G,h_data=2G,h_vmem=2G
#$ -cwd
#$ -j y
#$ -N trimmed
#$ -o trimmed.log
#
# ----------------Modules------------------------- #
module load bioinformatics/cutadapt/4.7
module load tools/R/4.4.1
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#

data="$1"
primerF="$2" 
primerR="$3"
primerFrc="$4"
primerRrc="$5"

if [ ! -z ${primerFrc} ]; then
  echo "Your gene has potential read-through, so we will attempt to trim primers from 3' read ends before 5'"
else
  echo "Your gene should have potential read-through, so we are only removing primers from the 5' end of each read."
fi


for x in ${data}/raw/*_R1*; do
  sample=`basename ${x}`
  name=$(echo ${sample} | awk -F'_S[0-9]{1,3}_' '{print $1}') 
  namepost=`echo ${sample#*_R[1-2]*}`
  namepre=`echo ${sample%*_R[1-2]*}`

if [[ ! -f ${namepre}_R2${namepost} ]]; then
  echo "Error, ${namepre}_R2${namepost} can not be found in data/raw/, please make sure all read pairs exist" >> "logs/cutadapt.log"
  exit 1
fi

if [ ! -z ${primerFrc} ]; then
  cutadapt \
  -a file:${data}/../primers/${primerRrc} \
  -A file:${data}/../primers/${primerFrc} \
  -e 0.2 --cores=$NSLOTS -O 10 --quiet \
  --json=logs/terminal_trim.cutadapt.json \
  -o ${data}/raw/${name}_trimmed_R1.fastq \
  -p ${data}/raw/${name}_trimmed_R2.fastq \
  ${data}/raw/${namepre}_R1${namepost} \
  ${data}/raw/${namepre}_R2${namepost}

  cutadapt \
  -g file:${data}/../primers/${primerF} \
  -G file:${data}/../primers/${primerR} \
  -e 0.2 --minimum-length 30 --cores=$NSLOTS --discard-untrimmed \
  --nextseq-trim=20 \
  --json=logs/front_trim.cutadapt.json \
  -o ${data}/working/trimmed_sequences/${name}_trimmed_R1.fastq \
  -p ${data}/working/trimmed_sequences/${name}_trimmed_R2.fastq \
  ${data}/raw/${name}_trimmed_R1.fastq \
  ${data}/raw/${name}_trimmed_R2.fastq

rm ${data}/raw/${name}_trimmed_R1.fastq ${data}/raw/${name}_trimmed_R2.fastq

else
  cutadapt \
  -g file:${data}/../primers/${primerF} \
  -G file:${data}/../primers/${primerR} \
  -e 0.2 --minimum-length 30 --cores=$NSLOTS --discard-untrimmed \
  --nextseq-trim=20 \
  --json=logs/front_trim.cutadapt.json \
  -o ${data}/working/trimmed_sequences/${name}_trimmed_R1.fastq \
  -p ${data}/working/trimmed_sequences/${name}_trimmed_R2.fastq \
  ${data}/raw/${namepre}_R1${namepost} \
  ${data}/raw/${namepre}_R2${namepost}
fi

gzip -2 \
${data}/working/trimmed_sequences/${name}_trimmed_R1.fastq \
${data}/working/trimmed_sequences/${name}_trimmed_R2.fastq 

done

Rscript 2_quality.R

echo = `date` job $JOB_NAME done