# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 4
#$ -q sThC.q
#$ -l mres=8G,h_data=2G,h_vmem=2G
#$ -cwd
#$ -j y
#$ -N trimmed
#$ -o trimmed.log
#
# ----------------Modules------------------------- #
module load bioinformatics/cutadapt/5.0
module load gcc/14.2.0
module load tools/R/4.4.1
module load tools/cmake
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#

#echo "$@"
num_genes="$1"  # First argument is the count of genes
#echo ${num_genes}
shift # Remove count argument
genes=("${@:1:$num_genes}")   # Uses number of genes to extract gene names
#echo "$genes"
shift "$num_genes" # remove gene arguments
#echo "$@"
path_to_data="$1" # Next argument is path to data directory
#echo "${path_to_data}"
shift # remove data argument
#echo ${@}
path_to_primers="$1" # Next argument is path to primers directory
# echo "${path_to_primers}"
shift
primer_files=("$@")  # assign remaining arguments as primers
#echo ${primer_files[@]}
#echo ${primer_files[1]}


primerF="${primer_files[0]}"
primerR="${primer_files[1]}"

# This is the standard loop to look in the raw files and get sample names
for x in ${path_to_data}/raw/*_R1*; do
  # Assign the name of the file to "sample"
  sample=${x##*/}
  # Assign the portion of the filename before barcode number to sample "name"
  name=$(echo ${sample} | awk -F'_S[0-9]{1,3}_' '{print $1}') 
  # Assign the portion of the filename after read direction to "namepost"
  namepost=${sample#*_R[1-2]*}
  # Assign the portion of the filename before read direction to "namepre"
  namepre=${sample%*_R[1-2]*}

#echo ${sample}
#echo ${name}
#echo ${namepost}
#echo ${namepre}
#echo ${path_to_data}/raw/${namepre}_R2${namepost}

  cutadapt \
  -g file:${primerF} \
  -G file:${primerR} \
  -e 0.2 --minimum-length 30 --cores=$NSLOTS --discard-untrimmed --quiet \
  -o "${path_to_data}/raw/demultiplexed_sequences/{name}/${name}_trimmed_R1.fastq" \
  -p "${path_to_data}/raw/demultiplexed_sequences/{name}/${name}_trimmed_R2.fastq" \
  "${path_to_data}/raw/${namepre}_R1${namepost}" \
  "${path_to_data}/raw/${namepre}_R2${namepost}"
done   

for gene in "${genes[@]}"; do
  if [[ -f "${path_to_primers}/${gene}-F_RC.fas" &&
        -f "${path_to_primers}/${gene}-R_RC.fas" ]]; then
    for x in ${path_to_data}/raw/demultiplexed_sequences/"${gene}"/*_R1*; do
      sample=${x##*/}
      name=${sample%_trimmed_R1.fastq}
      cutadapt \
      -a file:"${path_to_primers}/${gene}-F_RC.fas" \
      -A file:"${path_to_primers}/${gene}-R_RC.fas" \
      -e 0.2 --cores=$NSLOTS -O 6 --quiet --minimum-length 30 \
      -o "${path_to_data}/working/trimmed_sequences/${gene}/${name}_trimmed_R1.fastq" \
      -p "${path_to_data}/working/trimmed_sequences/${gene}/${name}_trimmed_R2.fastq" \
      "${path_to_data}/raw/demultiplexed_sequences/${gene}/${name}_trimmed_R1.fastq" \
      "${path_to_data}/raw/demultiplexed_sequences/${gene}/${name}_trimmed_R2.fastq"
    done
  else
    echo "Your reads for "${gene}" should not have potential read-through, so we only removed primers from the 5' end of each read."
    cp "${path_to_data}/raw/demultiplexed_sequences/${gene}/"* \
     "${path_to_data}/working/trimmed_sequences/${gene}/"
  fi
done

# This runs through each gene in the list of genes, and gzips all the fastq files
# in the gene-specific trimmed sequences folder   
for gene in "${genes[@]}"; do
  gzip -2 \
  "${path_to_data}/working/trimmed_sequences/${gene}/"*
done

# Finally, we start the R script for quality plot formation, passing the gene name as a variable
Rscript R_scripts/2_quality.R "${genes[@]}"

echo = `date` job $JOB_NAME done
