# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 20
#$ -q mThM.q
#$ -l mres=200G,h_data=10G,h_vmem=24G,himem
#$ -cwd
#$ -j y
#$ -N denoise
#$ -o logs/denoise.log
#
# ----------------Modules------------------------- #
module load tools/R/4.4.1
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
#echo ${@}
gene=${1}   # Extract gene name
r1=${2}
r2=${3}

#
# We only need the truncation values and number of genes for the filtering
Rscript R_scripts/3_filter.R ${gene} ${r1} ${r2}
# After filtering, since we are only passing the list of genes, we can get gene
# number from this
Rscript R_scripts/4_error.R ${gene}
Rscript R_scripts/5_denoise.R ${gene}
Rscript R_scripts/6_merge.R ${gene}
Rscript R_scripts/7_chimera.R ${gene}
Rscript R_scripts/8_output.R ${gene}
#
echo = `date` job $JOB_NAME done