# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 20
#$ -q mThM.q
#$ -l mres=200G,h_data=10G,h_vmem=16G,himem
#$ -cwd
#$ -j y
#$ -N denoise
#$ -o logs/denoise.log
#
# ----------------Modules------------------------- #
module load gcc/14.2.0
module load tools/R/4.4.1
module load tools/cmake
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
gene=${1}   # Extract gene name
#
# All arguments from shell script are just a list of genes, so we just pass on the
# entire array
Rscript R_scripts/5_denoise.R ${gene}
Rscript R_scripts/6_merge.R ${gene}
Rscript R_scripts/7_chimera.R ${gene}
Rscript R_scripts/8_output.R ${gene}
#
echo = `date` job $JOB_NAME done