# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 4
#$ -q sThM.q
#$ -l mres=48G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N denoise
#$ -o logs/denoise.log
#
# ----------------Modules------------------------- #
module load gcc/14.2.0
module load tools/R/4.4.1
module load tools/cmake
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
gene=${1}   # Extract gene name
#
# The only argument from the shell script is gene name, so we pass that to R
Rscript R_scripts/8_output.R ${gene}
#
echo = `date` job $JOB_NAME done