# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 12
#$ -q mThM.q
#$ -l mres=288G,h_data=24G,h_vmem=48G,himem
#$ -cwd
#$ -j y
#$ -N trimmed
#$ -o trimmed.log
#
# ----------------Modules------------------------- #
module load gcc/14.2.0
module load tools/R/4.4.1
module load tools/cmake
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
gene="$1"
#
# The only argument from the shell script is a gene, so we pass that to R
Rscript R_scripts/9_assign_taxonomy_dada2.R ${gene}
#
echo = `date` job $JOB_NAME done

