# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 12
#$ -q sThM.q
#$ -l mres=288G,h_data=24G,h_vmem=48G,himem
#$ -cwd
#$ -j y
#$ -N trimmed
#$ -o trimmed.log
#
# ----------------Modules------------------------- #
module load bioinformatics/blast

#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
gene="$1"
path_to_data="$2"
project_name="$3"

# This starts a blastn search against your reference database
# replace -query with the path to your representative sequence fasta
# replace -out with your desired out path.
# replace -db with the database you want to use. I don't know what is available
# on hydra currently
# Everything else should work
blastn \
-query ${path_to_data}/results/${gene}/${project_name}_rep-seq_${gene}.fas \
-db mito \
-task "blastn" \
-out ${path_to_data}/results/${gene}/${project_name}_blast_${gene}.tsv \
-num_threads $NSLOTS \
-max_target_seqs 5 \
-outfmt "6 qseqid sacc staxids sscinames scomnames qcovs pident"





echo = `date` job $JOB_NAME done