# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 12
#$ -q sThM.q
#$ -l mres=288G,h_data=24G,h_vmem=48G,himem
#$ -cwd
#$ -j y
#$ -N trimmed
#$ -o trimmed.log
#
# ----------------Modules------------------------- #
module load bioinformatics/cutadapt/4.7
module load tools/R/4.4.1
module load bioinformatics/blast
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
# This just starts the rescript for running the DADA2 identifier
Rscript ../R_scripts/assign_taxonomy.R

# This starts a blastn search against your reference database
# replace -query with the path to your representative sequence fasta
# replace -out with your desired out path.
# replace -db with the database you want to use. I don't know what is available
# on hydra currently
# Everything else should work
blastn \
-query /scratch/nmnh_lab/macdonaldk/pseudodec/data/working/PseudoDec_v2_rep-seq_md5.fas \
-db mito \
-task "blastn" \
-out /scratch/nmnh_lab/macdonaldk/pseudodec/data/results/meyer_pseudec_ind_v2_COI_blast.txt \
-num_threads $NSLOTS \
-max_target_seqs 10 \
-outfmt "6 qseqid sacc staxids sscinames qcovs pident"





echo = `date` job $JOB_NAME done